[package]
name = "run"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12.22", features = ["json"] }
chrono = "0.4.41"
